"""
Django settings for guardian project.

Generated by 'django-admin startproject' using Django 1.8.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

import os

from ConfigParser import RawConfigParser


BASE_DIR = os.path.dirname(os.path.abspath(__file__))

config = RawConfigParser()
config.read(''.join([BASE_DIR, os.getenv('sys_arg', '')]))


SECRET_KEY = '^7udybcxmmo#u!2j3x3c$wp*&n#8h5aw^d(2#v*#*4)a(-qrq_'

DEBUG = True

ALLOWED_HOSTS = []


LOGIN_URL = 'accounts:login'
LOGIN_REDIRECT_URL = 'main:home'
LOGOUT_URL = 'accounts:logout'


INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
    'main',
    'guardian',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'conf.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates'),],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'conf.wsgi.application'


DATABASES = {
    'default': {
        'ENGINE': ''.join(['django.db.backends.',
            config.get('sqlite3', 'DATABASE_ENGINE')]),
        'NAME': config.get('sqlite3', 'DATABASE_NAME'),
    }
}


LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_L10N = True

USE_TZ = False


STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
)

MEDIA_ROOT = os.path.join(BASE_DIR,'media')
MEDIA_URL = '/media/'
STATIC_ROOT = os.path.join(BASE_DIR,'static_files')
STATIC_URL = '/static/'

DATE_FORMAT_US = '%Y-%m-%d'
DATE_FORMAT_BR = '%d/%m/%Y'
DATETIME_FORMAT_BR = '%d/%m/%Y %H:%M:%S'